// ترجمان — فهرست زبان‌های ترجمه (زبان مقصد) و لحن‌ها
// هر ورودی: code (BCP-47 ساده), native (نام بومی), en (نام انگلیسی)
window.TARJOMAN_LANGS = [
  { code: 'fa', native: 'فارسی', en: 'Persian' },
  { code: 'en', native: 'English', en: 'English' },
  { code: 'ar', native: 'العربية', en: 'Arabic' },
  { code: 'tr', native: 'Türkçe', en: 'Turkish' },
  { code: 'fr', native: 'Français', en: 'French' },
  { code: 'de', native: 'Deutsch', en: 'German' },
  { code: 'es', native: 'Español', en: 'Spanish' },
  { code: 'pt', native: 'Português', en: 'Portuguese' },
  { code: 'it', native: 'Italiano', en: 'Italian' },
  { code: 'ru', native: 'Русский', en: 'Russian' },
  { code: 'zh', native: '中文', en: 'Chinese (Mandarin)' },
  { code: 'ja', native: '日本語', en: 'Japanese' },
  { code: 'ko', native: '한국어', en: 'Korean' },
  { code: 'hi', native: 'हिन्दी', en: 'Hindi' },
  { code: 'ur', native: 'اردو', en: 'Urdu' },
  { code: 'bn', native: 'বাংলা', en: 'Bengali' },
  { code: 'pa', native: 'ਪੰਜਾਬੀ', en: 'Punjabi' },
  { code: 'id', native: 'Bahasa Indonesia', en: 'Indonesian' },
  { code: 'ms', native: 'Bahasa Melayu', en: 'Malay' },
  { code: 'th', native: 'ไทย', en: 'Thai' },
  { code: 'vi', native: 'Tiếng Việt', en: 'Vietnamese' },
  { code: 'tl', native: 'Filipino', en: 'Filipino' },
  { code: 'my', native: 'မြန်မာ', en: 'Burmese' },
  { code: 'km', native: 'ខ្មែរ', en: 'Khmer' },
  { code: 'lo', native: 'ລາວ', en: 'Lao' },
  { code: 'ne', native: 'नेपाली', en: 'Nepali' },
  { code: 'si', native: 'සිංහල', en: 'Sinhala' },
  { code: 'ta', native: 'தமிழ்', en: 'Tamil' },
  { code: 'te', native: 'తెలుగు', en: 'Telugu' },
  { code: 'ml', native: 'മലയാളം', en: 'Malayalam' },
  { code: 'kn', native: 'ಕನ್ನಡ', en: 'Kannada' },
  { code: 'gu', native: 'ગુજરાતી', en: 'Gujarati' },
  { code: 'mr', native: 'मराठी', en: 'Marathi' },
  { code: 'he', native: 'עברית', en: 'Hebrew' },
  { code: 'ku', native: 'Kurdî', en: 'Kurdish' },
  { code: 'ps', native: 'پښتو', en: 'Pashto' },
  { code: 'az', native: 'Azərbaycan', en: 'Azerbaijani' },
  { code: 'uz', native: 'Oʻzbek', en: 'Uzbek' },
  { code: 'kk', native: 'Қазақ', en: 'Kazakh' },
  { code: 'ky', native: 'Кыргызча', en: 'Kyrgyz' },
  { code: 'tg', native: 'Тоҷикӣ', en: 'Tajik' },
  { code: 'tk', native: 'Türkmençe', en: 'Turkmen' },
  { code: 'mn', native: 'Монгол', en: 'Mongolian' },
  { code: 'hy', native: 'Հայերեն', en: 'Armenian' },
  { code: 'ka', native: 'ქართული', en: 'Georgian' },
  { code: 'el', native: 'Ελληνικά', en: 'Greek' },
  { code: 'nl', native: 'Nederlands', en: 'Dutch' },
  { code: 'sv', native: 'Svenska', en: 'Swedish' },
  { code: 'no', native: 'Norsk', en: 'Norwegian' },
  { code: 'da', native: 'Dansk', en: 'Danish' },
  { code: 'fi', native: 'Suomi', en: 'Finnish' },
  { code: 'is', native: 'Íslenska', en: 'Icelandic' },
  { code: 'pl', native: 'Polski', en: 'Polish' },
  { code: 'cs', native: 'Čeština', en: 'Czech' },
  { code: 'sk', native: 'Slovenčina', en: 'Slovak' },
  { code: 'hu', native: 'Magyar', en: 'Hungarian' },
  { code: 'ro', native: 'Română', en: 'Romanian' },
  { code: 'bg', native: 'Български', en: 'Bulgarian' },
  { code: 'sr', native: 'Српски', en: 'Serbian' },
  { code: 'hr', native: 'Hrvatski', en: 'Croatian' },
  { code: 'bs', native: 'Bosanski', en: 'Bosnian' },
  { code: 'sl', native: 'Slovenščina', en: 'Slovenian' },
  { code: 'mk', native: 'Македонски', en: 'Macedonian' },
  { code: 'sq', native: 'Shqip', en: 'Albanian' },
  { code: 'uk', native: 'Українська', en: 'Ukrainian' },
  { code: 'be', native: 'Беларуская', en: 'Belarusian' },
  { code: 'lt', native: 'Lietuvių', en: 'Lithuanian' },
  { code: 'lv', native: 'Latviešu', en: 'Latvian' },
  { code: 'et', native: 'Eesti', en: 'Estonian' },
  { code: 'sw', native: 'Kiswahili', en: 'Swahili' },
  { code: 'am', native: 'አማርኛ', en: 'Amharic' },
  { code: 'ha', native: 'Hausa', en: 'Hausa' },
  { code: 'yo', native: 'Yorùbá', en: 'Yoruba' },
  { code: 'ig', native: 'Igbo', en: 'Igbo' },
  { code: 'zu', native: 'isiZulu', en: 'Zulu' },
  { code: 'af', native: 'Afrikaans', en: 'Afrikaans' },
  { code: 'so', native: 'Soomaali', en: 'Somali' },
];

// لحن‌های ترجمه
window.TARJOMAN_TONES = [
  { id: 'literary',  fa: 'کتابی',     en: 'Literary',   ar: 'أدبي فصيح',  tr: 'Edebi' },
  { id: 'colloquial',fa: 'محاوره‌ای', en: 'Colloquial', ar: 'عامي دارج', tr: 'Günlük konuşma' },
  { id: 'cinematic', fa: 'سینمایی',   en: 'Cinematic',  ar: 'سينمائي',    tr: 'Sinematik' },
];
